name: build-deploy-js
on:
  # Trigger the workflow on merge,
  # but only for the source branch
  push:
    branches:
      - source
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install react-scripts
        run: npm install react-scripts
      - name: Build
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: main # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
